- name: Install DHCP server package (Debian/Ubuntu)
  apt:
      name: isc-dhcp-server
      state: present
  become: true

- name: Check if DHCP configuration file exists (Debian/Ubuntu)
  stat:
      path: /etc/dhcp/dhcpd.conf
  register: dhcpd_conf
  become: true

- name: Deploy DHCP server configuration file (Debian/Ubuntu)
  template:
      src: dhcpd.conf.j2
      dest: /etc/dhcp/dhcpd.conf
      owner: root
      group: root
      mode: "0644"
  notify: Restart Debian DHCP service
  become: true

- name: Ensure DHCP service is enabled and started (Debian/Ubuntu)
  service:
      name: isc-dhcp-server
      enabled: true
      state: started
  become: true
